version: '3'

services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=localhost
      - MONGO_URL=mongodb://db:27017/api
    depends_on:
      - db

  db:
    image: mongo
